image: ruby:2.2

pipelines:
  default:
    - step:
        script:
          - ruby --version
          - bundler --version
          - bundle install
          - bundle exec rspec
  branches:
    release:
      - step:
        script:
          - ruby --version
          - bundler --version
          - bundle install
          - bundle exec rspec
          - rake module:release
