image: ruby:2.1

pipelines:
  default:
    - step:
        script:
          - ruby --version
          - bundler --version
          - bundle install
          - rake spec
  branches:
    master:
      - step:
        script:
          - ruby --version
          - bundler --version
          - bundle install
          - rake spec
          - rake module:release
